#!/bin/bash

# # FOR PER-HANDLE VARIABLES:
# $ for i in `seq 0 9`; do cat foo.libneTest.write.stats.$i | egrep -A 4 '^erasure'| grep elapsed; done  | <this_script>
#
# # FOR PER-BLOCK VARIABLES:
# $ for i in `seq 0 9`; do cat foo.libneTest.write.stats.$i | egrep -A 4 '^erasure'| grep elapsed | <this_script>; done
#
#
# input to this script looks like this:
#
#     elapsed: 0.17265 sec, 172646.80667 usec, 172646806.66667 nsec
#     elapsed: 0.17337 sec, 173366.60000 usec, 173366600.00000 nsec
#     elapsed: 0.17266 sec, 172656.92333 usec, 172656923.33333 nsec
#     elapsed: 0.17298 sec, 172976.03333 usec, 172976033.33333 nsec
#     elapsed: 0.17512 sec, 175121.15333 usec, 175121153.33333 nsec
#     elapsed: 0.17328 sec, 173275.03667 usec, 173275036.66667 nsec
#     elapsed: 0.17265 sec, 172645.87667 usec, 172645876.66667 nsec
#     elapsed: 0.17384 sec, 173840.28333 usec, 173840283.33333 nsec
#     elapsed: 0.17354 sec, 173543.70667 usec, 173543706.66667 nsec
#     elapsed: 0.17418 sec, 174183.88333 usec, 174183883.33333 nsec
#


sed -e 's/  / /g; s/^ //' \
    | cut -d ' ' -f 2  \
    | R -q -e 'f <- file("stdin"); open(f); x <- read.csv(f, header = F); summary(x); sd(x[ , 1])' \
    | sed 's/:/ /' \
    | awk '/Min/{min=$2}
           /Max/{max=$2} 
           /Mean/{avg=$2}
           /\[1\]/{stddev=$2};
           END{printf("min: %f,  max: %f,  avg: %f,  std_dev: %f\n", min, max, avg, stddev)}'