#!/bin/bash

# shift cwd to this subdir
cd $( dirname $0 )

# create all linker objects
gcc -Wall -I ../../ -g -c ../../logging/logging.c
gcc -Wall -I ../../ -g -c ../thread_queue.c

# create the test executable
gcc -Wall -I ../ -g thread_queue.o logging.o testqueue.c -lpthread -o exectestqueue

# cleanup all linker objects
rm ./thread_queue.o ./logging.o

