#!/bin/bash
#
# Copyright (c) 2015, Los Alamos National Security, LLC
# All rights reserved.
# 
# Copyright 2015.  Los Alamos National Security, LLC. This software was produced
# under U.S. Government contract DE-AC52-06NA25396 for Los Alamos National
# Laboratory (LANL), which is operated by Los Alamos National Security, LLC for
# the U.S. Department of Energy. The U.S. Government has rights to use, reproduce,
# and distribute this software.  NEITHER THE GOVERNMENT NOR LOS ALAMOS NATIONAL
# SECURITY, LLC MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY LIABILITY
# FOR THE USE OF THIS SOFTWARE.  If software is modified to produce derivative
# works, such modified software should be clearly marked, so as not to confuse it
# with the version available from LANL.
#  
# Additionally, redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 3. Neither the name of Los Alamos National Security, LLC, Los Alamos National
# Laboratory, LANL, the U.S. Government, nor the names of its contributors may be
# used to endorse or promote products derived from this software without specific
# prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# -----
# NOTE:
# -----
# Although these files reside in a seperate repository, they fall under the MarFS copyright and license.
# 
# MarFS is released under the BSD license.
# 
# MarFS was reviewed and released by LANL under Los Alamos Computer Code identifier:
# LA-CC-15-039.
# 
# These erasure utilites make use of the Intel Intelligent Storage Acceleration Library (Intel ISA-L), which can be found at https://github.com/01org/isa-l and is under its own license.
# 
# MarFS uses libaws4c for Amazon S3 object communication. The original version
# is at https://aws.amazon.com/code/Amazon-S3/2601 and under the LGPL license.
# LANL added functionality to the original work. The original work plus
# LANL contributions is found at https://github.com/jti-lanl/aws4c.
# 
# GNU licenses can be found at http://www.gnu.org/licenses/.
#
# ----------------------------------------------------------------
#
# This is a very simple helper script that takes a list of MC paths (with %d for block) and outputs counts of 
#  data files, partial data files, manifests, and partial manifests.  It may be useful for diagnosing failed rebuilds.
#


if [[ $# -lt 1 ]]; then
   echo "missing argument - path list"
   exit -1
fi

cat $1 | while read -r line; do
   echo "$line"
   data_files=$(ls -l `echo "$line" | sed 's/%d/\*/'` 2>/dev/null )
   echo "`echo "$data_files" | wc -l` data files"
   #echo "$data_files" | sed 's/^/   /'
   manifests=$(ls -l `echo "$line" | sed 's/$/\.meta/' | sed 's/%d/\*/'` 2>/dev/null )
   if [[ $? -eq 0 ]]; then
      echo "`echo "$manifests" | wc -l` manifests"
    #  echo "$manifests" | sed 's/^/   /'
   fi
   part_data_files=$(ls -l `echo "$line" | sed 's/%d/\*/' | sed 's/$/.partial/'` 2>/dev/null )
   if [[ $? -eq 0 ]]; then
      echo "`echo "$part_data_files" | wc -l` partial data files"
     # echo "$part_data_files" | sed 's/^/   /'
   fi
   part_manifests=$(ls -l `echo "$line" | sed 's/$/\.partial.meta/' | sed 's/%d/\*/'` 2>/dev/null )
   if [[ $? -eq 0 ]]; then
      echo "`echo "$part_manifests" | wc -l` partial manifests"
    #  echo "$part_manifests" | sed 's/^/   /'
   fi
   echo
done

