#!/bin/bash

# shift cwd to this subdir
cd $( dirname $0 )

# create all linker objects
gcc -Wall -I ../../ -g -c ../../logging/logging.c
gcc -Wall -I ../../ -I /usr/lib/xml2 -g -c ../../dal/dal.c
gcc -Wall -I ../../ -g -c ../ioqueue.c

# create the test executable
gcc -Wall -I ../../ -g logging.o ioqueue.o test_ioqueue.c -lpthread -o exectestioqueue

# cleanup all linker objects
rm ./dal.o ./ioqueue.o ./logging.o

