name: MarFS CI
# There should be some way to use the workflow from the erasureUtils repo instead of duplicating the code from its
# workflow, but I haven't been able to get it to work, so we're going to do this manually

on:
  push:
  pull_request:

jobs:
  Build:
    env:
      Isal_assembler: nasm
      Ne_deps: "autoconf libxml2-dev"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ISA-L
      uses: actions/checkout@v3
      with:
        repository: intel/isa-l
        path: isa-l

    - name: Install ISA-L build dependencies
      run: sudo apt install $Isal_assembler

    - name: Build ISA-L
      run: |
        cd isa-l
        ./autogen.sh
        ./configure
        make
        sudo make install
    - name: Return to workspace root
      run: cd $GITHUB_WORKSPACE

    - name: Checkout erasureUtils
      uses: actions/checkout@v3
      with:
        repository: gransom/erasureUtils
        path: erasureUtils

    - name: Install erasureUtils build dependencies
      run: sudo apt install $Ne_deps

    - name: Build and check erasureUtils
      run: |
        cd erasureUtils
        mkdir install
        autoreconf -i
        ./configure --prefix=$PWD/install
        make check
        make install
        
    - name: Return to workspace root
      run: cd $GITHUB_WORKSPACE

