
name: erasureUtils CI


on:
  push:
  pull_request:
  workflow_call:

jobs:
  Build:
    env:
      Isal_assembler: nasm
      Ne_deps: "autoconf libxml2-dev openmpi-bin openmpi-common libopenmpi-dev libs3-dev rdmacm-utils"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ISA-L
      uses: actions/checkout@v3
      with:
        repository: intel/isa-l
        path: isa-l

    - name: Install ISA-L build dependencies
      run: sudo apt install $Isal_assembler

    - name: Build ISA-L
      run: |
        cd isa-l
        ./autogen.sh
        ./configure
        make
        sudo make install

    - name: Return to workspace root
      run: cd $GITHUB_WORKSPACE

    - name: Checkout erasureUtils
      uses: actions/checkout@v3
      with:
        path: erasureUtils

    - name: Install erasureUtils build dependencies
      run: sudo apt install $Ne_deps

    - name: Build and check erasureUtils
      continue-on-error: true
      run: |
        cd erasureUtils
        mkdir install
        autoreconf -i
        ./configure --prefix=$PWD/install
        make check
        make install

    - name: Dump Error Logs
      run: cat src/dal/*.log

    - name: Return to workspace root
      run: cd $GITHUB_WORKSPACE
